.travis.yml

Fixes #29 
To enable Travis CI builds.
Ensured build ran on https://travis-ci.com/paypal/NNAnalytics/builds/75449736
Ensured that it builds all supported Hadoop versions and checks findbugs, license, and tests

[#29] Create .travis.yml file for Travis CI

---

LICENSE
README.md

Fixes #32
Get the Apache 2.0 badge to display on the repo nav bar.
Followed steps for LICENSE template here: https://help.github.com/articles/adding-a-license-to-a-repository/

[#32] License file not detected

---

.travis.yml
build.gradle

Fixes #36 
Enable CodeCov support and processing.
Travis CI pushed CodeCov data to https://codecov.io/gh/paypal/NNAnalytics/commit/7eaa3b25ec44072a81f6ec933a6cff89b2352c10

[#36] Setup Codecov in Travis CI build

---

.travis.yml

Fixes #44 
- [] This pull request changes the code
This change mostly changes the build trigger logic used for Travis CI on Github

[#44] Skip CI for documentation-only PRs

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/SRandom.java
src/test/2.4.0/org/apache/hadoop/hdfs/server/namenode/GSetGenerator.java
src/test/2.6.1/org/apache/hadoop/hdfs/server/namenode/GSetGenerator.java
src/test/2.7.0/org/apache/hadoop/hdfs/server/namenode/GSetGenerator.java
src/test/2.8.0/org/apache/hadoop/hdfs/server/namenode/GSetGenerator.java
src/test/2.9.0/org/apache/hadoop/hdfs/server/namenode/GSetGenerator.java
src/test/3.0.0/org/apache/hadoop/hdfs/server/namenode/GSetGenerator.java
src/test/java/TestAuthorization.java
src/test/java/TestFinderQuery.java
src/test/java/TestINodeTransfer.java
src/test/java/TestLdapAuth.java
src/test/java/TestNNAnalytics.java
src/test/java/TestNoHistorical.java
src/test/java/TestQueryChecker.java
src/test/java/TestTransforms.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/GSetGeneratorBase.java

Fixes #3 
provide abstraction for GSetGenerator class so that every hadoop version dont have to implement it from scratch.
by running all the tests

[#3] abstract GSetGenerator

---

README.md
docs/_config.yml
docs/getting_started/How_To_Build.md
docs/getting_started/How_To_Configure.md
docs/getting_started/How_To_Install.md
docs/getting_started/How_To_Run.md
docs/getting_started/How_To_Test.md
docs/getting_started/supported_versions.md
docs/index.md

Fixes #2 
- First cut of read the docs integration
- Please see this link for how the documents would render once the PR is merged. https://nnanalytics-1.readthedocs.io/en/latest/
- Refer https://nnanalytics-1.readthedocs.io/en/latest/
1. Adding the integration of "readthedocs" in the github settings.
2. Configuring the build of master in readthedocs.org
3. Adding the docs build status badge into the readme.md 

[#2] Document the web API

---

src/main/java/com/paypal/namenode/NNAnalyticsRestAPI.java
src/main/java/com/paypal/security/SecurityConfiguration.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/NNLoader.java
src/test/resources/security.properties

[#34] Make suggestions reload sleep configurable

---

README.md

Fixes #11
Add the badges for codacy and readthedocs.
No code changes.

[#11] Add badges for readthedocs & codacy

---

docs/Getting_Started/How_To_Build.md
docs/Getting_Started/How_To_Run.md
docs/Getting_Started/Supported_Hadoop_Versions.md
docs/Getting_Started/Supported_Operating_Systems.md
docs/index.md

Fixes #57 
Update documentation
Validated locally. Will check with build of readthedocs for this branch.

[#57] Organize and update documentation

---

README.md

[#65] Fix Codacy badge and organize badges

---

src/main/resources/public/navbar.html

Fixes #63 
This is in an attempt to fix the following broken 'Total' queries:
- Sum of all Empty Files
- Sum of all Empty Directories
- Sum of all Snapshot'd Files
- Total Snapshot'd Diskspace

#63 Fixed a few of the 'filters' lines to 'filter'

---

.gitignore
build.gradle
docs/Getting_Started/How_To_Test.md
src/main/java/com/paypal/namenode/NNAnalyticsRestAPI.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/NNLoader.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/CacheManager.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java
src/test/java/TestAuthorization.java
src/test/java/TestFinderQuery.java
src/test/java/TestLdapAuth.java
src/test/java/TestNNAnalytics.java
src/test/java/TestNoHistorical.java
src/test/java/TestQueryChecker.java
src/test/java/TestTransforms.java
src/test/java/TestWithMiniCluster.java
src/test/resources/security.properties

Fixes #8 
Enhance testing to utilize full HDFS stack w/ Journal Nodes.
Unit tests ran for all supported Hadoop versions:
```
./gradlew clean assemble build -PhadoopVersion=2.4.0 -x findbugsMain -x findbugsTest
./gradlew clean assemble build -PhadoopVersion=2.6.1 -x findbugsMain -x findbugsTest
./gradlew clean assemble build -PhadoopVersion=2.7.0 -x findbugsMain -x findbugsTest
./gradlew clean assemble build -PhadoopVersion=2.8.0 -x findbugsMain -x findbugsTest
./gradlew clean assemble build -PhadoopVersion=2.9.0 -x findbugsMain -x findbugsTest
./gradlew clean assemble build -PhadoopVersion=3.0.0 -x findbugsMain -x findbugsTest
```
3. Subject does not end …

[#8] Utilize MiniDFSCluster for testing

---

docs/Getting_Started/How_To_Build.md
docs/Getting_Started/Supported_Hadoop_Versions.md
docs/Getting_Started/Supported_Operating_Systems.md
docs/Query_Parameters/6_Finds.md
docs/index.md

[#72] Document how finds work

---

src/main/resources/config/security.properties
src/test/resources/security.properties

[#75] Re-organize configuration properties

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java
src/main/java/org/apache/hadoop/util/VirtualINode.java
src/main/java/org/apache/hadoop/util/VirtualINodeTree.java
src/test/java/TestVirtualTree.java

Fixes #15 
Unit test addition.
Ran unit tests.

[#15] Add test for VirtualINodeTree

---

.travis.yml
docs/Getting_Started/How_To_Test.md
src/main/java/com/paypal/namenode/HSQLDriver.java
src/main/java/com/paypal/namenode/NNAnalyticsRestAPI.java
src/main/java/com/paypal/security/SecurityConfiguration.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/NNLoader.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/CacheManager.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java
src/main/resources/config/security.properties
src/test/java/TestAuthorization.java
src/test/java/TestFinderQuery.java
src/test/java/TestLdapAuth.java
src/test/java/TestNNAnalytics.java
src/test/java/TestNoHistorical.java
src/test/java/TestQueryChecker.java
src/test/java/TestTransforms.java
src/test/java/TestWithMiniCluster.java
src/test/resources/security.properties

[#30] Make hardcoded paths configurable

---

src/main/java/com/paypal/namenode/NNAnalyticsRestAPI.java
src/main/java/com/paypal/security/SecurityConfiguration.java
src/main/java/com/paypal/security/SecurityContext.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/NNAConstants.java
src/main/resources/config/security.properties
src/main/resources/public/custom.html
src/main/resources/public/division.html
src/main/resources/public/history.html
src/main/resources/public/index.html
src/main/resources/public/js/nna.utility.js
src/main/resources/public/login.html
src/main/resources/public/logout.html
src/main/resources/public/namespace.html
src/main/resources/public/qoutas.html
src/main/resources/public/report.html
src/main/resources/public/showcase.html
src/main/resources/public/suggestion.html
src/main/resources/public/tidy.html
src/main/resources/public/tokens.html
src/main/resources/public/transform.html
src/main/resources/public/value.html
src/test/java/TestLdapAuth.java
src/test/java/TestNNAnalytics.java
src/test/resources/security.properties

[#26] Add a /logout endpoint

---

src/main/java/com/paypal/namenode/NNAnalyticsRestAPI.java
src/main/java/com/paypal/security/SecurityContext.java
src/main/resources/public/custom.html
src/main/resources/public/division.html
src/main/resources/public/history.html
src/main/resources/public/index.html
src/main/resources/public/js/nna.utility.js
src/main/resources/public/namespace.html
src/main/resources/public/navbar.html
src/main/resources/public/qoutas.html
src/main/resources/public/report.html
src/main/resources/public/showcase.html
src/main/resources/public/suggestion.html
src/main/resources/public/tidy.html
src/main/resources/public/tokens.html
src/main/resources/public/transform.html
src/main/resources/public/value.html
src/test/java/TestLdapAuth.java
src/test/java/TestNNAnalytics.java

[#68] Admin tab on navbar fails intermittently

---

src/main/java/com/paypal/security/SecurityContext.java
src/test/java/TestLdapAuth.java

[#84] Restore LDAP basic authentication

---

.travis.yml
README.md
src/main/java/com/paypal/namenode/HSQLDriver.java
src/main/java/com/paypal/namenode/NNAnalyticsRestAPI.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/NNLoader.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/operations/BaseOperation.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/operations/Delete.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/operations/OperationLog.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/operations/SetReplication.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/operations/SetStoragePolicy.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/queries/Transforms.java
src/test/java/TestBaseQuery.java
src/test/java/TestFinderQuery.java
src/test/java/TestGSetCollectionWrapper.java
src/test/java/TestLdapAuth.java
src/test/java/TestNNAnalytics.java
src/test/java/TestOperations.java
src/test/java/TestTransforms.java
src/test/java/TestWithMiniCluster.java

[#59] Increase code coverage

---

build.gradle

[#89] Add exception format printing to build

---

src/test/java/TestWithMiniCluster.java

[#91] TestWithMiniCluster.testSaveNamespace failing randomly

---

README.md
build.gradle
docs/Getting_Started/How_To_Test.md
src/test/java/com/paypal/nnanalytics/TestAuthorization.java
src/test/java/com/paypal/nnanalytics/TestBaseQuery.java
src/test/java/com/paypal/nnanalytics/TestFinderQuery.java
src/test/java/com/paypal/nnanalytics/TestGSetCollectionWrapper.java
src/test/java/com/paypal/nnanalytics/TestINodeTransfer.java
src/test/java/com/paypal/nnanalytics/TestLdapAuth.java
src/test/java/com/paypal/nnanalytics/TestNNAnalytics.java
src/test/java/com/paypal/nnanalytics/TestNoHistorical.java
src/test/java/com/paypal/nnanalytics/TestOperations.java
src/test/java/com/paypal/nnanalytics/TestQueryChecker.java
src/test/java/com/paypal/nnanalytics/TestTransforms.java
src/test/java/com/paypal/nnanalytics/TestVirtualTree.java
src/test/java/com/paypal/nnanalytics/TestWithMiniCluster.java

[#70] Move unpackaged tests to com.paypal package

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/queries/FileTypeHistogram.java
src/main/resources/public/suggestion.html

Fixes #98
Ran the MiniCluster demo and ensured that FileType histograms still working as intended.
Measured performance of 500k file types at the worst case scenario (UNKNOWN file types) -- saw that at 500k files the previous implementation against a 3.2GHz, 4 core machine, came to about 2 seconds and new implementation takes about 900ms. In the fast case the new implementation performs in under 100ms meanwhile the old implement was between 200-500ms, depending how many iterations it had to check against.
This implementation is clearly a benefit for the file type histogram.
For fun I also added more extension types.
4. …

[#98] Add HashMap to extension checking of FileType histogram

---

src/main/resources/public/namespace.html

Fixes #100 
Validated against MiniCluster of all versions.

[#100] Fix failing javascript in namespace.html

---

.travis.yml
build.gradle

Fixes #96
To put in the framework for ensuring that we can create release packages in the future.

[#96] Standardize on versioning and releases

---

.travis.yml

[#114] Travis build must occur for tags

---

.travis.yml

[#116] Add encrypted token to Travis YAML for deploy

---

docs/Getting_Started/How_To_Configure.md
src/main/java/com/paypal/security/SecurityConfiguration.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeLoader.java
src/main/resources/config/core-site.blank.xml
src/main/resources/config/hdfs-site.blank.xml
src/main/resources/config/security.properties
src/test/java/com/paypal/nnanalytics/TestWithMiniCluster.java
src/test/resources/security.properties

Fixes #127
See #127.
No cluster validation. Only on mini-cluster.

[#127] Make configuration overrides optional

---

build.gradle
src/main/resources/config/security.properties

Fixes #133 
- [ x ] This pull request changes the code
- [ x ] Title of the PR is of format (example) : `[#25] Add Pull Request Template`, where `[#25] is the GitHub issue number`
- [ x ] My commits all reference GH issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":

[#133] Fix Debian builds

---

build.gradle

[#136] Current builds are always using the last tag

---

docs/REST_Endpoints/Token.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java
src/main/java/org/apache/hadoop/security/token/delegation/TokenExtractor.java
src/main/resources/public/tokens.html

[#142] Tokens endpoint should provide usernames who never had a token issued

---

mkdocs.yml

[#148] Add mkdocs.yml file

---

src/main/resources/public/users.html
src/test/java/com/paypal/nnanalytics/TestWithMiniClusterBase.java

[#151] Improve users.html page by adding percentage of old files

---

docs/REST_Endpoints/Dump.md
src/main/2.4.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/2.6.1/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/2.7.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/2.8.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/2.9.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/3.0.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/java/com/paypal/namenode/WebServerMain.java

[#156] Convert /dump output to JSON

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/queries/FileTypeHistogram.java

[#161] Increase file type discovery

---

src/main/resources/public/navbar.html

[#163] Add quotas.html to navbar

---

src/main/java/com/paypal/namenode/UsageMetrics.java
src/main/java/com/paypal/security/SecurityContext.java

[#167] Provide methods in UsageMetrics and SecurityContext to work with raw HttpServlets

---

src/main/resources/public/suggestion.html

[#169] Suggestions page rendering bad token dates

---

src/main/java/com/paypal/security/SecurityConfiguration.java
src/main/java/com/paypal/security/SecurityContext.java
src/test/java/com/paypal/nnanalytics/TestLdapAuth.java

[#171] Support passwordless authentication

---

src/main/resources/public/quotas.html

[#173] Quota tables HTML page has wrong order

---

docs/REST_Endpoints/Histogram.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/queries/Histograms.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestNNAnalyticsBase.java

[#179] Provide a way to get the raw timestamps from CSV output Histogram queries

---

docs/Query_Parameters/Filters.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractQueryEngine.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/Constants.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/JavaCollectionQEngine.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestNNAnalyticsBase.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestWithMiniClusterBase.java

Provide a filter for check if an inode is under a quota

---

docs/Query_Parameters/Filters.md
docs/Query_Parameters/Histograms.md
docs/Query_Parameters/Sums.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractQueryEngine.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/JavaCollectionQEngine.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/JavaStreamQueryEngine.java

[#185] Modify filesystem object size in memoryConsumed query

---

docs/REST_Endpoints/GetCachedQuery.md
docs/REST_Endpoints/RemoveCachedQuery.md
docs/REST_Endpoints/SetCachedQuery.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/Constants.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/CacheManager.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestNNAnalyticsBase.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestOperations.java

[#184] Allow users to cache queries for report generation

---

docs/Getting_Started/How_To_Configure.md
docs/Getting_Started/How_To_Install.md
docs/REST_Endpoints/GetCachedQuery.md
docs/REST_Endpoints/Histogram.md
docs/REST_Endpoints/Info.md
docs/REST_Endpoints/SetCachedQuery.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestNNAnalyticsBase.java

[#188] Improvements to cached queries

---

src/main/resources/bin/nn-analytics

[#193] Increase sleep time for restart function

---

build.gradle

[#198] Releases are built/executed/released in the context of insecure/untrusted code

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java

[#194] Reduce output size when using suggestions?all API

---

docs/Query_Parameters/Filters.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractQueryEngine.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestWithMiniClusterBase.java

[#195] Ignore the namespace quota on root directory

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java

[#203] Add finer grained logging of time spent in Suggestions queries

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/security/SecurityContext.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/queries/Histograms.java

Fixes #207 
The log message type was changed to debug from info.

[#207] Modified info log messages to debug

---

.travis.yml
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/operations/BaseOperation.java

[#214] Upload failed build test reports to transfer.sh

---

build.gradle
src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractQueryEngine.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/Constants.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/JavaCollectionQEngine.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/test/3.0.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestHadoopNNAAuthorization.java
src/test/3.0.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestHadoopNNAOperations.java
src/test/3.1.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestHadoopNNAAuthorization.java
src/test/3.1.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestHadoopNNAOperations.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestAuthorizationBase.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestNNAnalyticsBase.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestOperationsBase.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestWebServerMainAuthorization.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestWebServerMainOperations.java
src/test/java/org/apache/hadoop/security/token/delegation/TestTokenExtractor.java

[#216] Improve code coverage

---

build.gradle

[#218] Debian builds attempt to make use of chkconfig

---

docs/Query_Parameters/CachedMaps.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/Constants.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java
src/main/resources/webapps/nna/cachedReport.html
src/main/resources/webapps/nna/css/nna.css
src/main/resources/webapps/nna/history.html
src/main/resources/webapps/nna/js/nna.utility.js
src/main/resources/webapps/nna/navbar.html
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestWithMiniClusterBase.java

[#220] Split UI into Queries and Cached Reports and expose cached reports

---

docs/REST_Endpoints/Quotas.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/CachedQuotas.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java
src/main/resources/webapps/nna/js/nna.utility.js
src/main/resources/webapps/nna/navbar.html
src/main/resources/webapps/nna/quotas.html
src/main/resources/webapps/nna/suggestion.html
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestWithMiniClusterBase.java

[#229] Actual numbers report for Space and Namespace quotas

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/queries/FileTypeHistogram.java

[#232] Add more file types into FileTypeHistogram

---

build.gradle
docs/Getting_Started/How_To_Configure.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/ApplicationConfiguration.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/NameNodeAnalyticsHttpServer.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/CachedDirectories.java
src/main/resources/config/application.properties
src/main/resources/env/nna_env
src/test/3.0.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestHadoopNNAAuthorization.java
src/test/3.0.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestHadoopNNAOperations.java
src/test/3.0.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestHadoopNNAWithStreamEngine.java
src/test/3.0.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestMiniClusterHadoopNNAWithStreamEngine.java
src/test/3.1.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestHadoopNNAAuthorization.java
src/test/3.1.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestHadoopNNAOperations.java
src/test/3.1.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestHadoopNNAWithStreamEngine.java
src/test/3.1.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestMiniClusterHadoopNNAWithStreamEngine.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestLdapAuth.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestNNAWithStreamEngine.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestNoHistorical.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestWebServerMainAuthorization.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestWebServerMainOperations.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestWithMiniClusterWithStreamEngine.java
src/test/resources/application.properties

[#223] Externalize web resources

---

src/main/resources/webapps/nna/css/bootstrap.css
src/main/resources/webapps/nna/css/nna.css
src/main/resources/webapps/nna/js/nna.utility.js
src/main/resources/webapps/nna/suggestion.html

[#209] Add an [Explain] button for Totals

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/queries/FileTypeHistogram.java

[#245] Add more file types

---

docs/Query_Parameters/Sums.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractQueryEngine.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/Constants.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/Helper.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/queries/FileTypeHistogram.java

[#247] Add dirNumChildren summation for dirs set sums

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeLoader.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestNNAnalyticsBase.java

[#250] Dump endpoint can cause Error

---

src/main/resources/webapps/nna/suggestion.html

[#249] Add pointer to trenner/ahar in Suggestions page

---

.travis.yml
build.gradle
docs/REST_Endpoints/SQL.md
docs/index.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/HistogramInvoker.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/sql/INodeSqlStatementVisitor.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/sql/SqlParser.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/main/resources/webapps/nna/navbar.html
src/main/resources/webapps/nna/sql.html
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestNNAnalyticsBase.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestSQL.java

[#258] Add a SQL-like API

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/Constants.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/sql/INodeSqlStatementVisitor.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/sql/SqlParser.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/main/resources/webapps/nna/sql.html
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestSQL.java

[#260] SQL aggregation functions not working

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/HistogramInvoker.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/sql/INodeSqlStatementVisitor.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/sql/SqlParser.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java

[#263] Support ASC and DESC sorting in SQL command

---

src/main/resources/webapps/nna/sql.html

[#262] Dump SQL response into Datatables

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/sql/INodeSqlStatementVisitor.java

[#266] Parse accessTime and modTime dates for SQL queries

---

src/main/resources/webapps/nna/sql.html

[#269] Provide error message output on SQL page

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/sql/INodeSqlStatementVisitor.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/sql/SqlParser.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/main/resources/webapps/nna/sql.html

[#270] Allow setting of user variables in SQL page

---

docs/REST_Endpoints/Histogram2.md
src/main/2.7.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/2.8.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/2.9.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/3.0.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/3.1.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractQueryEngine.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/Constants.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/QueryEngine.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/VersionInterface.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/HistogramInvoker.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/HistogramTwoLevelInvoker.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/queries/FileTypeHistogram.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/queries/Histograms.java
src/main/resources/webapps/nna/histogram2.html
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestNNAnalyticsBase.java

Refactor query engine to make way for two-level grouping.

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeLoader.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/ApplicationConfiguration.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/HadoopWebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/security/KeytabReloader.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsReloader.java
src/main/resources/config/application.properties
src/test/3.0.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestMiniClusterHadoopNNAWithStreamEngine.java
src/test/3.1.0/org/apache/hadoop/hdfs/server/namenode/analytics/TestMiniClusterHadoopNNAWithStreamEngine.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestWithMiniClusterBase.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestWithMiniClusterWithStreamEngine.java

[#275] Provide easier restart functionality

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java

[#276] Add display for how many transactions NNA is behind

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeLoader.java
src/main/resources/webapps/nna/histogram.html

[#279] Provide histogram.html page

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/CachedQuotas.java

[#281] Improve cached quotas by using two level histograms

---

docs/REST_Endpoints/FileTypes.md
docs/index.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractQueryEngine.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/Constants.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/CachedFileTypes.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/cache/SuggestionsEngine.java
src/main/resources/webapps/nna/fileTypes.html
src/main/resources/webapps/nna/navbar.html
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestNNAnalyticsBase.java

[#283] Add file type histogram to SuggestionsEngine

---

src/main/resources/webapps/nna/navbar.html

[#285] Add query links for finding directories with no quotas

---

src/main/resources/webapps/nna/fileTypes.html

[#287] fileTypes.html not producing correct results

---

src/main/java/org/apache/hadoop/hdfs/server/namenode/Constants.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/HadoopWebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/NameNodeAnalyticsHttpServer.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/WebServerMain.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/web/NamenodeAnalyticsMethods.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/queries/BaseQuery.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestNNAnalyticsBase.java

[#290] Add admin API to kill running queries

---

build.gradle
docs/Getting_Started/How_To_Configure.md
src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractQueryEngine.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/ConcurrentHashMapINodeCollection.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/EclipseINodeCollection.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/HashMapINodeCollection.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeFilterer.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeLoader.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/QueryEngine.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/TroveINodeCollection.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/analytics/ApplicationConfiguration.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/BenchmarkGSetFiltering.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/MemoryProfiler.java
src/test/java/org/apache/hadoop/hdfs/server/namenode/analytics/TestFiltererLoading.java

[#230] Investigate using different Collections libraries for filter speed-up

---

build.gradle

[#301] Build failing with commons-io

---

.github/workflows/gradle.yml

[#303] Store RPM, DEB, and Reports as artifacts in GitHub Actions

---

.github/workflows/gradle.yml
build.gradle
docs/Getting_Started/Supported_Hadoop_Versions.md
src/main/2.10.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/2.10.0/org/apache/hadoop/util/GSetSeperatorWrapper.java
src/main/2.7.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/2.8.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/2.9.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/3.1.0/org/apache/hadoop/hdfs/server/namenode/VersionContext.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeLoader.java
src/main/java/org/apache/hadoop/hdfs/server/namenode/VersionInterface.java
src/test/2.10.0/org/apache/hadoop/hdfs/server/namenode/GSetGenerator.java

- Adding option to build NNA with HDFS 2.10.0
- Fix problem with dependency on commons-io
- Add eclipse plugin

Add support for HDFS 2.10.0
